routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'LandingController@index')->name('index');
Route::post('/cari', 'LandingController@pencarian')->name('cari');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/pengaduan/store', 'LandingController@PengaduanStore')->name('aduan.store');

Route::group(['prefix'=>'admin','as'=>'admin.'],function (){
	Route::get('/home','HomeController@index')->name('home');

	Route::get('/kandidat/profil','KandidatController@profil')->name('profil');
	Route::get('/kandidat/document','KandidatController@document')->name('document');
	Route::get('/lpz/tbsyarat/{slug}','KandidatController@syarat')->name('syarat');
	Route::POST('/lpz/url_pdf/{slug}','KandidatController@url_pdf')->name('url_pdf');
	Route::POST('/lpz/upload_file','KandidatController@upload_file')->name('upload_file');
	Route::POST('/lpz/del_pdf','KandidatController@del_pdf')->name('del_pdf');

	Route::get('/kandidat/getdist','KandidatController@getdist')->name('getdist');
	Route::get('/lpz/tbgetdist/{slug}','KandidatController@tbgetdist')->name('tbgetdist');
	Route::post('/api/getdist','KandidatController@getdistapi')->name('getdistapi');
	Route::get('/api/deletenrc/{slug}','KandidatController@deletenrc')->name('deletenrc');
	Route::get('/api/shownrc/{slug}','KandidatController@shownrc')->name('shownrc');

	Route::get('/audit/import','AuditController@import')->name('import');
	Route::get('/audit/kinerja','AuditController@kinerja')->name('kinerja');
	Route::get('/audit/kinerja_nilai/{slug}','AuditController@kinerja_nilai')->name('kinerja_nilai');
	Route::post('/audit/postkinerja','AuditController@postkinerja')->name('postkinerja');
	Route::post('/audit/nilaikinerja','AuditController@nilaikinerja')->name('nilaikinerja');
	Route::get('/audit/kepatuhan','AuditController@kepatuhan')->name('kepatuhan');
	Route::get('/audit/kepatuhan_nilai/{slug}','AuditController@kepatuhan_nilai')->name('kepatuhan_nilai');
	Route::post('/audit/postnilai','AuditController@postnilai')->name('postnilai');
	Route::post('/audit/getsubnilai','AuditController@getsubnilai')->name('getsubnilai');

	Route::get('/lembaga/verifikasi','LembagaController@verifikasi')->name('verifikasi');
	Route::post('/lembaga/verifikasi/update','LembagaController@update')->name('editverifikasi');

	Route::GET('/aduan', 'PengaduanController@index')->name('aduan');

	Route::GET('/user', 'UserController@index')->name('user');
	Route::GET('/loaduser', 'UserController@loaduser')->name('loaduser');
	Route::POST('/saveuser', 'UserController@store')->name('saveuser');
	Route::GET('/deleteuser/{slug}', 'UserController@delete')->name('deleteuser');
	Route::GET('/showuser/{slug}', 'UserController@show')->name('showuser');

	Route::GET('/showgroup/{id}','UserController@showgroup');
	Route::POST('/tambah-akses','UserController@tambahAkses');
	Route::GET('/akses-data/{id}','UserController@AksesData');
	Route::GET('/akses-hapus/{id}','UserController@AksesHapus');

	Route::get('/question','HomeController@index')->name('question');

});

app/Http/Controllers/AuditController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use DB;

class AuditController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');
    }

    public function import(){
    	$title = "Import Data LPZ";
    	$user = User::all();
    	return view('audit.importdatalaz',compact('title','user'));
    }




    public function kinerja(){
    	$title = "Kinerja Keuangan";
    	return view('audit.kinerja',compact('title'));
    }




    public function kinerja_nilai($id){
    	$title = "Kinerja Keuangan";
    	return view('audit.kinerja_nilai',compact('title','id'));
    }



    public function postkinerja(Request $request){
    	$user_id = $request->user_id;
      	$kin_no = $request->kin_no;
		$kin_subno = $request->kin_subno;
		
		
      	$nilai = $request->nilai;
      	$con = DB::connection('mysql');
      	$kin_val = '';
      	if($nilai==4){
        	$kin_val = 'A';
      	}elseif ($nilai==3) {
        	$kin_val = 'B';
      	}elseif ($nilai==2) {
        	$kin_val = 'C';
      	}elseif ($nilai==1) {
        	$kin_val = 'D';
      	}else {
        	$kin_val = 'E';
      	}
      	$sql = "select * from lpz_kinerja where user_id = '$user_id' and kin_no = '$kin_no' and kin_subno = '$kin_subno'";
      	$cnt = $con->select($sql);
      	if(count($cnt)==1){
			echo "update";
			echo "update lpz_kinerja set kin_val='$kin_val', kin_skor='$nilai' where user_id = '$user_id' and kin_no = '$kin_no' and kin_subno = '$kin_subno'";
        	$con->Select("update lpz_kinerja set kin_val='$kin_val', kin_skor='$nilai' where user_id = '$user_id' and kin_no = '$kin_no' and kin_subno = '$kin_subno'");
      	}else{
			echo "insert";
        	$con->select("insert into lpz_kinerja(user_id,kin_no,kin_subno,kin_val,kin_skor)values('$user_id','$kin_no','$kin_subno','$kin_val','$nilai')");
      	}
    }



    public function nilaikinerja(Request $request){
      $user = $request->user_id;
      $con = DB::connection('mysql');
      $sql = "select sum(a.kin_skor * b.kin_bobot) skor from lpz_kinerja a LEFT JOIN mst_kinerja b ON (a.kin_no=b.kin_no and a.kin_subno=b.kin_subno) where a.user_id = '$user'";
      $cnt = $con->select($sql);
      if(count($cnt)==1){
        $data = $con->select($sql);
        echo $data[0]->skor;
      }else {
        echo 0;
      }
    }




    public function kepatuhan(){
    	$title = "Penilaian Kepatuhan Syariah";
    	return view('audit.kepatuhan',compact('title'));
    }



    public function kepatuhan_nilai($id){
    	$title = "Penilaian Kepatuhan Syariah";
    	return view('audit.kepatuhan_nilai',compact('title','id'));
    }


    public function postnilai(Request $request){
    	$con = DB::connection('mysql');
      	$user_id = $request->user_id;
      	$patuh_subno = $request->patuh_subno;
      	$patuh_val = $request->patuh_val;
      	$patuh_skor = $request->patuh_skor;
      	$sql = "select * from lpz_kepatuhan where user_id = '$user_id' and patuh_subno = '$patuh_subno'";
      	$cnt = $con->select($sql);
      	if(count($cnt)==1){
        	$con->select("update lpz_kepatuhan set patuh_val='$patuh_val', patuh_skor='$patuh_skor' where user_id = '$user_id' and patuh_subno = '$patuh_subno'");
      	}else{
        	$con->select("insert into lpz_kepatuhan(user_id,patuh_subno,patuh_val,patuh_skor)values('$user_id','$patuh_subno','$patuh_val','$patuh_skor')");
      	}
    }


    public function getsubnilai(Request $request){
    	$con = DB::connection('mysql');
      	$user = $request->user_id;
      	$sub = $request->sub;
      	$sql = "select sum(patuh_skor) as sumskor from lpz_kepatuhan where user_id = '$user' and substr(patuh_subno,1,locate('.',patuh_subno)-1) = '$sub' GROUP BY id,substr(patuh_subno,1,locate('.',patuh_subno)-1)";
      	$cnt = $con->select($sql);
      	if(count($cnt)==1){
        	$data = $con->select($sql);
        	echo $data[0]->sumskor;
      	}else {
        	echo 0;
      	}
    }
}

resources/views/audit/importdatalaz.blade.php
@extends('layouts.adminlte')

@section('content')

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{{$title}}</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn-sm  btn btn-success" name="button" onclick="newentry();"><i class="fa fa-plus-circle"></i>Tambah</button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive">


        Pilih Lembaga : 
        <div class="row">
          <div class="col-sm-4">
            <select class="form-control mb-2" name="pilem" id="pilem" onselect="GetTable()">
              <option value="">-Pilih-</option>
              @foreach($user as $dt)
              <option value="{{$dt->id}}">{{$dt->name}}</option>
              @endforeach
            </select>
          </div>
          <div class="col-sm-6">
            <i id="progress" name="progress"></i>
            <input type="hidden" name="pil_user" id="pil_user" value="0">
            <input type="hidden" name="pil_name" id="pil_name" value="--">
          </div>
        </div>


        <table class="table table-striped">
          <thead>
            <tr class="bg-warning">
              <th rowspan="2">Periode</th>
              <th colspan="4">Perolehan</th>
              <th colspan="3">Pendistribusian</th>
              <th rowspan="2" colspan="1">Saldo</th>
              <th rowspan="2" colspan="2">Action</th>
            </tr>
            <tr class="bg-warning">
              <th>Zakat</th>
              <th>Infaq</th>
              <th>Dana Sosial Keagamaan Lainnya</th>
              <th>Total</th>
              <th>Konsumtif</th>
              <th>Produktif</th>
              <th>Total</th>
            </tr>
          </thead>  
          <tbody id="isitb">
            
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->

  </div>
  <!-- /.col -->
</div>
<!-- /.row -->



<!-- Modal -->
<div class="modal fade" id="modalcrud" tabindex="-1" aria-labelledby="modalcrudLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header">
        <h5 class="modal-title" id="modalcrudLabel">Entry Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <input type="hidden" name="id" id="id" value="0">
          <div class="col-md-8">
            <label for="">Nama Lembaga :</label>
            <input type="text" name="nama_lembaga" id="nama_lembaga" class="form-control" readonly/>
          </div>
          
          <div class="col-md-4 ml-auto">
            <label for="startDate">Periode :</label>
              <div class="datepicker-wrap">
                <div class="input-group">
                  <input type="text" class="form-control periode" placeholder="MM/YYYY" id="datepicker-input">
                  <span class="input-group-btn">
                      <button class="btn btn-default" type="button" id="datepicker-btn"><i class="fa fa-calendar" aria-hidden="true"></i></button>
                  </span>
                </div>
              </div>
          </div>

          <div class="col-md-12">
            <hr>
            <b>Perolehan : </b>
            <hr>
          </div>

          <div class="col-md-4 ">
            <label for="">Zakat</label>
            <input class="form-control" name="zakat" id="zakat" style="text-align:right" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" onblur="curr(this.name)">
          </div>
          
          <div class="col-md-4 ml-auto">
            <label for="">Infaq</label>
            <input class="form-control" name="infaq" id="infaq" style="text-align:right" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" onblur="curr(this.name)">
          </div>

          <div class="col-md-4 ml-auto">
            <label for="">Lainnya</label>
            <input class="form-control" name="lainnya" id="lainnya" style="text-align:right" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" onblur="curr(this.name)">
          </div>

          <div class="col-md-12">
            <hr>
            <b>Pendistribusian : </b>
            <hr>
          </div>

          <div class="col-md-6">
            <label for="">Konsumtif</label>
            <input class="form-control" name="konsumtif" id="konsumtif" style="text-align:right" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" onblur="curr(this.name)">
          </div>
          <div class="col-md-6">
            <label for="">Produktif</label>
            <input class="form-control" name="produktif" id="produktif" style="text-align:right" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" onblur="curr(this.name)">
          </div>
        </div>
        
      </div>
      <div class="modal-footer">
         <input type="hidden" name="act" id="act" value="new">
        <input onclick="saveData()" type="button" class="btn btn-success" value="Simpan Data">
      </div>
    </div>
  </div>
</div>


@endsection


@section('js')
<script type="text/javascript">
  
  function curr(name){
    var val = parseInt($('#' + name).val().replace(/[^0-9\.-]+/g,""));
    if(isNaN(val)){
      val = 0;
    }
    while (/(\d+)(\d{3})/.test(val.toString())){
      val = val.toString().replace(/(\d+)(\d{3})/, '$1'+','+'$2');
    }
    $('#'+name).val(val);
  }

  function tocurr(val){
      while (/(\d+)(\d{3})/.test(val.toString())){
        val = val.toString().replace(/(\d+)(\d{3})/, '$1'+','+'$2');
      }
      return val;
  }


  function clearItem(){
    $('#periode').val('');
    $('#zakat').val('');
    $('#infaq').val('');
    $('#lainnya').val('');
    $('#konsumtif').val('');
    $('#produktif').val('');
    $('#act').val('new');
  }



  function saveData(){
    var act = $('#act').val();
    var user_id = $('#pil_user').val();

    var id = $('#id').val();
    var periode = $('.periode').val();
    var zakat = parseInt($('#zakat').val().replace(/[^0-9\.-]+/g,""));
    var infaq = parseInt($('#infaq').val().replace(/[^0-9\.-]+/g,""));
    var dansos_lain = parseInt($('#lainnya').val().replace(/[^0-9\.-]+/g,""));
    var total_peroleh = zakat + infaq + dansos_lain;

    var konsumtif = parseInt($('#konsumtif').val().replace(/[^0-9\.-]+/g,""));
    var produktif = parseInt($('#produktif').val().replace(/[^0-9\.-]+/g,""));
    var total_distribusi = konsumtif + produktif ;

    var saldo = parseInt(total_peroleh) - parseInt(total_distribusi);
    if(periode==''){
      alert('Periode tidak boleh kosong');
      exit;
    }
    if(act=='new'){
      act = 'insert';
    }else{
      act = 'update';
    }
    $.ajax({
      "url":"{{url('admin/api/getdist')}}",
      "data": {act:act,id:id,user_id:user_id,periode:periode,zakat:zakat,infaq:infaq,dansos_lain:dansos_lain,total_peroleh:total_peroleh,konsumtif:konsumtif,produktif:produktif,total_distribusi:total_distribusi,saldo:saldo, "_token": "{{ csrf_token() }}"},
      "type":"POST",
      "dataType" :"json",
      "success":function(result){
          var hasil = JSON.parse(JSON.stringify(result));
          var cek = hasil.status;
          if(cek == 'Success'){
            loaddata(user_id);
            $('#modalcrud').modal('hide');
            clearItem();
          }else{
            alert(hasil.msg);
          }
      },
      "error":function(jqXHR, textStatus, errorThrown){
        alert(jqXHR.responseText);
      }
    });
  }



  function showedit(id){
    $("#progress").html('<img src="http://webzakat.esy.es/assets/images/ajax-loading30.gif">');
    $.ajax({
      "url":"{{url('admin/api/shownrc')}}/"+ id,
      "type": "GET",
      "dataType" : "json",
      "success":function(result){
         var hasil = JSON.parse(JSON.stringify(result));
         var res = JSON.parse(JSON.stringify(hasil.data));
          $('#act').val(hasil.data[0].id);
          $('#id').val(hasil.data[0].id);
          $('.periode').val(hasil.data[0].periode);
          $('#zakat').val(tocurr(hasil.data[0].zakat));
          $('#infaq').val(tocurr(hasil.data[0].infaq));
          $('#lainnya').val(tocurr(hasil.data[0].dansos_lain));
          $('#konsumtif').val(tocurr(hasil.data[0].konsumtif));
          $('#produktif').val(tocurr(hasil.data[0].produktif));
          $('#modalcrud').modal('show');
          $("#progress").html('');
      }
    });
  }



  function showdel(id) {
    var r = confirm("Are you sure you want to delete this Record?");
    if (r == true) {
        $("#progress").html('<img src="http://webzakat.esy.es/assets/images/ajax-loading30.gif">');
        $.ajax({
          "url":"{{url('admin/api/deletenrc')}}/"+ id,
          "type": "GET",
          "dataType" : "json",
          "success":function(result){
            var hasil = JSON.parse(JSON.stringify(result));
            var cek = hasil.status;
            if(cek == 'Success'){
              loaddata($('#pil_user').val());
              $("#progress").html('');
            }else{
              alert(hasil.msg);
            }
          }
        });
    }
  }

  


  loaddata($('#pil_user').val());
  function loaddata(id) {
    $("#progress").html('<img src="http://webzakat.esy.es/assets/images/ajax-loading30.gif">');
    $('#callbtn').html('<input type="submit" class="btn btn-info" value="Save" disabled>');
    $.ajax({
      "url": "{{url('admin/lpz/tbgetdist')}}/"+id,
      "type":"GET",
      "success":function(data){
        document.getElementById('isitb').innerHTML = data;
        $("#progress").html('');
        if(id==0){
          $('#callbtn').html('<input type="submit" class="btn btn-info" value="Save" disabled>');
        }else {
          $('#callbtn').html('<input type="submit" class="btn btn-info" value="Save">');
        }
      }
    });
  }



$(function(){
  var selCategory = $('#pilem');
  $(selCategory).change(function() {
    $('option:selected').each(function() {
      loaddata($(this).val());
      $('#pil_user').val($(this).val());
      $('#pil_name').val($(this).text());
      $('#nama_lembaga').val($(this).text());
    });
  });
});

function newentry() {
  if($('#pil_user').val()!=0){
    $('#modalcrud').modal('show');
  }else {
    alert('Nama lembaga tidak boleh kosong');
  } 
}

</script>
@endsection

resources/views/audit/kepatuhan.blade.php
@extends('layouts.adminlte')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-outline card-warning">
        <div class="card-header with-border">
          <h3 class="card-title">{{$title}}</h3>
          
        </div><!-- /.card-header -->
        <div class="card-body">
            <table id="datatable" class="table table-striped">
              <thead>
                <tr class="bg-warning">
                  <th>No</th>
                  <th>Nama Lembaga</th>
                  <th>Skor</th>
                  <th>Nilai</th>
                  <th>Status</th>
                  <th>Penilaian</th>
                </tr>
              </thead>  
              <tbody>
                <?php
                $con = DB::Connection('mysql');
                $data = $con->select("select a.user_id,name,IFNULL(skor,0) skor,if(ifnull(skor,0)>0,ifnull(skor,0)/340*100,0) nilai,if(penilaian=34,'Full',if(penilaian>0,'Partial','-')) penilaian from users a LEFT JOIN (select user_id,ifnull(sum(patuh_skor),0) as skor,COUNT(patuh_skor) penilaian from lpz_kepatuhan GROUP BY user_id) b on a.user_id=b.user_id WHERE a.user_type IN ('BAZ','LAZ','BBI')");
                $n=1;
                foreach ($data as $row) {
                   echo '<tr style="background-color:white">
                    <td>'.$n.'</td>
                    <td>'.$row->name.'</td>
                    <td align="center">'.$row->skor.'</td>
                    <td align="center">'.number_format($row->nilai,0).'</td>
                    <td align="center">'.$row->penilaian.'</td>
                    <td align="center"><a href="'.url('admin/audit/kepatuhan_nilai/'.$row->user_id).'"  class="btn btn-info"> Pilih</a></td>
                  </tr>';
                  $n++;
                }
                ?>  
              </tbody>
            </table>
        </div><!-- /.card-body -->
      </div><!-- /.card -->
    </div>
</div>


@endsection


@section('js')
  <script type="text/javascript">
  $("#datatable").DataTable({
  "paging": true,
  "lengthChange": false,
  "searching": true,
  "ordering": true,
  "info": true,
  "autoWidth": false,
  "responsive": true,
});

</script>

@endsection

resources/views/audit/kepatuhan_nilai.blade.php
@extends('layouts.adminlte')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-outline card-warning">
        <div class="card-header with-border">
          <h3 class="card-title">
            <?php
              $con = DB::connection('mysql');
              $user = $id;
              $data = $con->select("select * from users where user_id like '$user'");
              foreach ($data as $col) {
                echo 'Nama Lembaga : '.$col->name.'';
                echo '<input type="hidden" name="pil_user" id="pil_user" value="'.$user.'">';
              }
            ?>  // Monev Kepatuhan Syariah <?=date('Y');?>
          </h3>
          
        </div><!-- /.card-header -->
        <div class="card-body">


          <?php
            $con = DB::connection('mysql');
            $sub = $con->select("select patuh_no from mst_kepatuhan group by patuh_no");
            foreach ($sub as $col) {
              $subno = $col->patuh_no;
              ?>

              <table id="tb" border="1" class="table table-striped">
                <thead>
                  <tr class="bg-warning">
                    <th rowspan="2" align="center" width="40px">No</th>
                    <th rowspan="2" align="center" width="20%">Unsur</th>
                    <th rowspan="2" colspan="2" align="center">Variabel</th>
                    <th rowspan="1" colspan="2" align="center" class="col-md-2">Score</th>
                  </tr>
                  <tr  class="bg-warning">
                    <th align="center" width="10%">Ya/Sebagian/Tidak</th>
                    <th align="center" width="10%">Nilai</th>
                  </tr>
                </thead>
                <tbody id="isitb">

                  <?php
                  $no = 0;
                  $sql = "select a.patuh_no,c.unsur,a.patuh_subno,patuh_variabel,ifnull(patuh_val,'x') patuh_val,patuh_skor,user_id FROM mst_kepatuhan a LEFT JOIN lpz_kepatuhan b ON (a.patuh_subno=b.patuh_subno and b.user_id = '$user') LEFT JOIN (select patuh_no,patuh_variabel as unsur from mst_kepatuhan WHERE patuh_subno=concat(patuh_no,'.0')) c on a.patuh_no=c.patuh_no WHERE a.patuh_subno <> CONCAT(a.patuh_no,'.0') and a.patuh_no = '$subno' order by a.patuh_subno";
                  $data = $con->select($sql);
                  $count = count($data);

                  for($i=0;$i<$count;$i++){
                    if($no!=$data[$i]->patuh_no){
                      echo '<tr><td align="center">'.$data[$i]->patuh_no.'</td><td>'.$data[$i]->unsur.'</td>';
                    }else {
                      echo "<tr><td></td><td></td>";
                    }

                    $a = $i +1;
                    $subno1 = substr($data[$i]->patuh_subno,stripos($data[$i]->patuh_subno,'.')+1,5);
                    $subno3 = '';
                    if(stripos($subno1,".")>0){
                      $subno2 = substr($subno1,0,-stripos($subno1,".")-1);
                      $subno3 = substr($subno1,stripos($subno1,'.')+1,5);
                    }else {
                      $subno2 = $subno1;
                    }
                    if($subno3==''){
                      $var = $subno2;
                    }else {
                      $var = '('.$subno3.')';
                    }

                    $r1 = '';
                    $r2 = '';
                    $r3 = '';
                    if($data[$i]->patuh_val=='2'){
                      $r1 = 'checked';
                      $r2 = '';
                      $r3 = '';
                    }elseif($data[$i]->patuh_val=='1'){
                      $r2 = 'checked';
                      $r1 = '';
                      $r3 = '';
                    }elseif($data[$i]->patuh_val=='0'){
                      $r2 = '';
                      $r3 = '';
                      $r3 = 'checked';
                    }else{
                      $r1 = '';
                      $r2 = '';
                      $r3 = '';
                    }

                    $nila = 0;
                    if($data[$i]->patuh_skor!=''){
                      $nila = $data[$i]->patuh_skor;
                    }
                    echo '<td align="center" width="30px" valign="top">'.$var.'</td>
                          <td valign="top">'.$data[$i]->patuh_variabel.'</td>';
                    if($data[$i]->patuh_subno!='1.5'){
                    echo '<td align="left" valign="top">
                          <form action="">
                              <input type="radio" name="'.$data[$i]->patuh_subno.'" value="Ya" onclick="setnilai(this.name,10,2)" '.$r1.'> Ya <br>
                              <input type="radio" name="'.$data[$i]->patuh_subno.'" value="Sebagian" onclick="setnilai(this.name,5,1)" '.$r2.'> Sebagian <br>
                              <input type="radio" name="'.$data[$i]->patuh_subno.'" value="Tidak" onclick="setnilai(this.name,0,0)" '.$r3.'> Tidak
                          </form>
                          </td>
                          <td align="center"><span id="'.$data[$i]->patuh_subno.'">'.$nila.'</span><input type="hidden" class="'.$subno.'" id="dum_'.$data[$i]->patuh_subno.'" value="0"></td>
                      </tr>';
                    }else {
                      echo '<td align="center" valign="top" colspan="2">
                            </td>
                        </tr>';
                    }

                    $no = $data[$i]->patuh_no;
                  }

                  if($subno==1){
                    echo '<tr class="bg-warning"><td></td><td colspan="4" align="center"><b>Jumlah Total Skor Aspek pengumpulan</b></td><td align="center"><b><span id="nil1">0</span></b></td></tr>';
                  }elseif ($subno==2) {
                    echo '<tr class="bg-warning"><td></td><td colspan="4" align="center"><b>Jumlah Score aspek pendistribusian dan pendayagunaan</b></td><td align="center"><b><span id="nil2">0</span></b></td></tr>';
                  }elseif ($subno==3) {
                    echo '<tr class="bg-warning"><td></td><td colspan="4" align="center"><b>Jumlah Score aspek pengelolaan keuangan</b></td><td align="center"><b><span id="nil3">0</span></b></td></tr>';
                  }
                  ?>
                </tbody>
              </table>
              <?php
            }
          ?>



        </div><!-- /.card-body -->
        <div class="card card-footer">
          <a href="{{route('admin.kepatuhan')}}" class="btn btn-info btn-block">Kembali</a>
          <input type="button" class="btn btn-info btn-block" onclick="relaodAlldata()" value="Refresh">
        </div>
      </div><!-- /.card -->
    </div>
</div>


@endsection


@section('js')
<script type="text/javascript">
 
  function setnilai(id,nil,val) {
    var user_id = $('#pil_user').val();
    $.ajax({
      "url":"{{route('admin.postnilai')}}",
      "type":"post",
      "data":{user_id:user_id,patuh_subno:id,patuh_val:val,patuh_skor:nil,"_token": "{{ csrf_token() }}"},
      "success":function() {
        document.getElementById(id).innerHTML = nil;
        document.getElementById('dum_'+id).value = nil;
        reloadNilai(1);
        reloadNilai(2);
        reloadNilai(3);
      }
    });
  }



  function reloadNilai(x) {
    var user_id = $('#pil_user').val();
    $.ajax({
      "url":"{{route('admin.getsubnilai')}}",
      "type":"post",
      "data":{user_id:user_id,sub:x,"_token": "{{ csrf_token() }}"},
      "success":function(data) {
          $('#nil'+x).html(data);
      }
    });
  }
  function relaodAlldata() {
    reloadNilai(1);
    reloadNilai(2);
    reloadNilai(3);
  }
  $(document).ready(function(){
    relaodAlldata();
  });
</script>
@endsection