routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'LandingController@index')->name('index');
Route::post('/cari', 'LandingController@pencarian')->name('cari');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/pengaduan/store', 'LandingController@PengaduanStore')->name('aduan.store');

Route::group(['prefix'=>'admin','as'=>'admin.'],function (){
	Route::get('/home','HomeController@index')->name('home');

	Route::get('/kandidat/profil','KandidatController@profil')->name('profil');
	Route::get('/kandidat/document','KandidatController@document')->name('document');
	Route::get('/lpz/tbsyarat/{slug}','KandidatController@syarat')->name('syarat');
	Route::POST('/lpz/url_pdf/{slug}','KandidatController@url_pdf')->name('url_pdf');
	Route::POST('/lpz/upload_file','KandidatController@upload_file')->name('upload_file');
	Route::POST('/lpz/del_pdf','KandidatController@del_pdf')->name('del_pdf');

	Route::get('/kandidat/getdist','KandidatController@getdist')->name('getdist');
	Route::get('/lpz/tbgetdist/{slug}','KandidatController@tbgetdist')->name('tbgetdist');
	Route::post('/api/getdist','KandidatController@getdistapi')->name('getdistapi');
	Route::get('/api/deletenrc/{slug}','KandidatController@deletenrc')->name('deletenrc');
	Route::get('/api/shownrc/{slug}','KandidatController@shownrc')->name('shownrc');

	Route::get('/audit/import','AuditController@import')->name('import');
	Route::get('/audit/kinerja','AuditController@kinerja')->name('kinerja');
	Route::get('/audit/kinerja_nilai/{slug}','AuditController@kinerja_nilai')->name('kinerja_nilai');
	Route::post('/audit/postkinerja','AuditController@postkinerja')->name('postkinerja');
	Route::post('/audit/nilaikinerja','AuditController@nilaikinerja')->name('nilaikinerja');
	Route::get('/audit/kepatuhan','AuditController@kepatuhan')->name('kepatuhan');
	Route::get('/audit/kepatuhan_nilai/{slug}','AuditController@kepatuhan_nilai')->name('kepatuhan_nilai');
	Route::post('/audit/postnilai','AuditController@postnilai')->name('postnilai');
	Route::post('/audit/getsubnilai','AuditController@getsubnilai')->name('getsubnilai');

	Route::get('/lembaga/verifikasi','LembagaController@verifikasi')->name('verifikasi');
	Route::post('/lembaga/verifikasi/update','LembagaController@update')->name('editverifikasi');

	Route::GET('/aduan', 'PengaduanController@index')->name('aduan');

	Route::GET('/user', 'UserController@index')->name('user');
	Route::GET('/loaduser', 'UserController@loaduser')->name('loaduser');
	Route::POST('/saveuser', 'UserController@store')->name('saveuser');
	Route::GET('/deleteuser/{slug}', 'UserController@delete')->name('deleteuser');
	Route::GET('/showuser/{slug}', 'UserController@show')->name('showuser');

	Route::GET('/showgroup/{id}','UserController@showgroup');
	Route::POST('/tambah-akses','UserController@tambahAkses');
	Route::GET('/akses-data/{id}','UserController@AksesData');
	Route::GET('/akses-hapus/{id}','UserController@AksesHapus');

	Route::get('/question','HomeController@index')->name('question');

});

app/Http/Controllers/LembagaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\User;
class LembagaController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function verifikasi(){
    	$title = "Verifikasi";
    	$user = User::all();
    	return view('lembaga.verifikasi',compact('title','user'));
    }

    public function update(Request $request){
    	$id = $request->id;
    	$user = User::findorfail($id);
    	$user->verified = $request->verifikasi;
    	$user->save();
    	return redirect('admin/lembaga/verifikasi')->with('status', 'Data Buku Berhasil Ditambahkan');
    }
}

resources/views/lembaga/verifikasi.blade.php
@extends('layouts.adminlte')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card card-outline card-warning">
        <div class="card-header with-border">
          <h3 class="card-title">{{$title}}</h3>
          
        </div><!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Alamat</th>
                  <th>Email</th>
                  <th>Telp</th>
                  <th>Lat</th>
                  <th>Lng</th>
                  <th>Verifikasi</th>
                  <th>Opsi</th>
                </tr>
              </thead>
              <tbody>
                @foreach($user as $d)
                <tr>
                  <td>{{$loop->iteration}}</td>
                  <td>{{$d->name}}</td>
                  <td>{{$d->alamat}}</td>
                  <td>{{$d->email}}</td>
                  <td>{{$d->no_telp}}</td>
                  <td>{{$d->lat}}</td>
                  <td>{{$d->lng}}</td>
                  <td>
                    
                    @if($d->verified == 'Y')
                      <i class="fa fa-check-circle bg-success p-1"></i> 
                    @else
                      <i class="fa fa-times-circle-o bg-danger p-1"></i>
                    @endif
                  </td>
                  <td>
                    <a href="#" data-toggle="modal" data-target="#exampleModal<?=$d->id?>" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
        </div><!-- /.card-body -->
      </div><!-- /.card -->
    </div>
</div>



<!-- Modal -->
@foreach($user as $d)
<div class="modal fade" id="exampleModal<?=$d->id?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Verifikasi</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{route('admin.editverifikasi')}}" method="post">
        @csrf
        <input type="hidden" name="id" value="{{$d->id}}">
      <div class="modal-body">
        <select class="form-control" name='verifikasi' id="verifikasi">
          <option value="">Pilih</option>
          <option value="Y" <?=$d->verified == 'Y' ? 'selected' : ''?> >Yes</option>
          <option value="N" <?=$d->verified == 'N' ? 'selected' : ''?>>No</option>
        </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
 @endforeach

@endsection


@section('js')
<script type="text/javascript">
  
  $("#example1").DataTable({
  "paging": true,
  "lengthChange": false,
  "searching": true,
  "ordering": true,
  "info": true,
  "autoWidth": false,
  "responsive": true,
});


</script>

@endsection