routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'LandingController@index')->name('index');
Route::post('/cari', 'LandingController@pencarian')->name('cari');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/pengaduan/store', 'LandingController@PengaduanStore')->name('aduan.store');

Route::group(['prefix'=>'admin','as'=>'admin.'],function (){
	Route::get('/home','HomeController@index')->name('home');

	Route::get('/kandidat/profil','KandidatController@profil')->name('profil');
	Route::get('/kandidat/document','KandidatController@document')->name('document');
	Route::get('/lpz/tbsyarat/{slug}','KandidatController@syarat')->name('syarat');
	Route::POST('/lpz/url_pdf/{slug}','KandidatController@url_pdf')->name('url_pdf');
	Route::POST('/lpz/upload_file','KandidatController@upload_file')->name('upload_file');
	Route::POST('/lpz/del_pdf','KandidatController@del_pdf')->name('del_pdf');

	Route::get('/kandidat/getdist','KandidatController@getdist')->name('getdist');
	Route::get('/lpz/tbgetdist/{slug}','KandidatController@tbgetdist')->name('tbgetdist');
	Route::post('/api/getdist','KandidatController@getdistapi')->name('getdistapi');
	Route::get('/api/deletenrc/{slug}','KandidatController@deletenrc')->name('deletenrc');
	Route::get('/api/shownrc/{slug}','KandidatController@shownrc')->name('shownrc');

	Route::get('/audit/import','AuditController@import')->name('import');
	Route::get('/audit/kinerja','AuditController@kinerja')->name('kinerja');
	Route::get('/audit/kinerja_nilai/{slug}','AuditController@kinerja_nilai')->name('kinerja_nilai');
	Route::post('/audit/postkinerja','AuditController@postkinerja')->name('postkinerja');
	Route::post('/audit/nilaikinerja','AuditController@nilaikinerja')->name('nilaikinerja');
	Route::get('/audit/kepatuhan','AuditController@kepatuhan')->name('kepatuhan');
	Route::get('/audit/kepatuhan_nilai/{slug}','AuditController@kepatuhan_nilai')->name('kepatuhan_nilai');
	Route::post('/audit/postnilai','AuditController@postnilai')->name('postnilai');
	Route::post('/audit/getsubnilai','AuditController@getsubnilai')->name('getsubnilai');

	Route::get('/lembaga/verifikasi','LembagaController@verifikasi')->name('verifikasi');
	Route::post('/lembaga/verifikasi/update','LembagaController@update')->name('editverifikasi');

	Route::GET('/aduan', 'PengaduanController@index')->name('aduan');

	Route::GET('/user', 'UserController@index')->name('user');
	Route::GET('/loaduser', 'UserController@loaduser')->name('loaduser');
	Route::POST('/saveuser', 'UserController@store')->name('saveuser');
	Route::GET('/deleteuser/{slug}', 'UserController@delete')->name('deleteuser');
	Route::GET('/showuser/{slug}', 'UserController@show')->name('showuser');

	Route::GET('/showgroup/{id}','UserController@showgroup');
	Route::POST('/tambah-akses','UserController@tambahAkses');
	Route::GET('/akses-data/{id}','UserController@AksesData');
	Route::GET('/akses-hapus/{id}','UserController@AksesHapus');

	Route::get('/question','HomeController@index')->name('question');

});

resources/views/layouts/#app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/adminlte.blade.php
<?php
  $path_asset = asset('bower_components/adminlte').'/';
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Halaman Admin - Sistem Informasi Zakat</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{{asset('mobapp/images/logo-depag.png')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{$path_asset}}plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{$path_asset}}plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="{{$path_asset}}plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{$path_asset}}dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- FontAwesome 4.3.0 -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <!-- Ionicons 2.0.0 -->
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />    


  <!-- <link rel="stylesheet" type="text/css" href="{{url('css/daterangepicker.css')}}" />
  <script type="text/javascript" src="http://zakat.smartcorp.co.id/assets/js/daterangepicker.js"></script> -->

  <!-- DataTables -->
  <link rel="stylesheet" href="{{$path_asset}}plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="{{$path_asset}}plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <style type="text/css"> 
      .navbar-success {
        background-color: rgba(3, 89, 11);
      }

      .btn-success{
        background-color: rgba(3, 89, 11);
      }
    </style>
</head>
<body class="hold-transition sidebar-mini layout-fixed ">
<div class="wrapper">
  @include('layouts.menu')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{$title}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{{$title}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          @yield('content')
      </div>
      
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <!-- <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div> -->
    <strong>Copyright &copy; 2020 Kementrian Agama Republik Indonesia
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<!-- <script src="{{$path_asset}}plugins/jquery/jquery.min.js"></script> -->
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<!-- Bootstrap 4 -->
<script src="{{$path_asset}}plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables -->
<script src="{{$path_asset}}plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{$path_asset}}plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{$path_asset}}plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{$path_asset}}plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<!-- AdminLTE App -->
<script src="{{$path_asset}}dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{$path_asset}}dist/js/demo.js"></script>

<script type="text/javascript" src="{{url('js/daterangepicker.js')}}"></script>


@yield('js')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/menu.blade.php
<?php
use \App\MenuGroup;
use \App\MenuUser;

$user_id = Auth::user()->id;
$group = MenuGroup::where('user_id',$user_id)->get();
$group_id = $group[0]->id;
?>
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-light navbar-success">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button" ><i class="fas fa-bars" style="color:#fff"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link"  style="color:#fff;font-size:16px">Login : {{ucwords(Auth::user()->user_type)}}</a>
      </li>
     <!--  <li class="nav-item d-none d-sm-inline-block">
        <a href="{{$path_asset}}index3.html" class="nav-link"  style="color:#fff">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link" style="color:#fff">Contact</a>
      </li> -->
    </ul>

    

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar elevation-4 sidebar-light-success">
    <!-- Brand Logo -->
    <a href="{{$path_asset}}index3.html" class="brand-link navbar-success">
      <img src="{{asset('mobapp/images/logo-depag.png')}}"
           alt="AdminLTE Logo"
           class="brand-image"
           style="opacity: .8">
      <span class="brand-text" style="color:#fff;font-size: 16px">LEMBAGA AMIL ZAKAT</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('images/profil.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item ">
            <a href="{{route('admin.home')}}" class="nav-link {{ url('/admin/home') == request()->url() ? 'active' : '' }}">
              <i class="nav-icon fas fa-home"></i>
              <p>Beranda</p>
            </a>
          </li>

          <?php
          $menu = MenuUser::where('group_id',$group_id)->where('menu','LPZ')->get();
          ?>
          @if ($menu->COUNT() <> 0)
          <li class="nav-item has-treeview {{ url('/admin/kandidat/profil') == request()->url() || url('/admin/kandidat/document') == request()->url() || url('/admin/kandidat/getdist') == request()->url() ?  'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>
                LPZ
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('admin.profil')}}" class="nav-link {{ url('/admin/kandidat/profil') == request()->url() ? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>
                  <p>Profile</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.document')}}" class="nav-link {{ url('/admin/kandidat/document') == request()->url() ? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>
                  <p>Upload Document</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.getdist')}}" class="nav-link {{ url('/admin/kandidat/getdist') == request()->url() ? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>                  
                  <p>Perolehan & Distribusi</p>
                </a>
              </li>
            </ul>
          </li>
          @endif


          <?php
          $menu = MenuUser::where('group_id',$group_id)->where('menu','Akreditasi & Audit')->get();
          ?>
          @if ($menu->COUNT() <> 0)
          <li class="nav-item has-treeview {{ url('/admin/audit/import') == request()->url() || 
                            url('/admin/audit/kinerja') == request()->url() ||
                            url('/admin/audit/kepatuhan') == request()->url() || 
                            Request::segment(3) == 'kinerja_nilai' ||
                            Request::segment(3) == 'kepatuhan_nilai' ?  'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>
                Akreditasi & Audit
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview ">
              <li class="nav-item">
                <a href="{{route('admin.import')}}" class="nav-link {{ url('/admin/audit/import') == request()->url() ? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>
                  <p>Import Data LPZ</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.kinerja')}}" class="nav-link {{ url('/admin/audit/kinerja') == request()->url() || 
                                  Request::segment(3) == 'kinerja_nilai' ? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>
                  <p>Penilaian Akreditasi</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.kepatuhan')}}" class="nav-link {{ url('/admin/audit/kepatuhan') == request()->url() || 
                                  Request::segment(3) == 'kepatuhan_nilai'? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>
                  <p>Kepatuhan Syariah</p>
                </a>
              </li>
            </ul>
          </li>
          @endif
     
          
          <?php
          $menu = MenuUser::where('group_id',$group_id)->where('menu','Lembaga & Info Zawa')->get();
          ?>
          @if ($menu->COUNT() <> 0)
          <li class="nav-item has-treeview {{ url('/admin/lembaga/verifikasi') == request()->url() ?  'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>
                Lembaga & Info Zawa
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('admin.verifikasi')}}" class="nav-link {{ url('/admin/lembaga/verifikasi') == request()->url() ? 'active' : '' }}">
                  <i class="fas fa-check-circle nav-icon"></i>
                  <p>Verifikasi</p>
                </a>
              </li>
            </ul>
          </li>
          @endif
         

          <?php
          $menu = MenuUser::where('group_id',$group_id)->where('menu','Pengaduan Masyarakat')->get();
          ?>
          @if ($menu->COUNT() <> 0)
          <li class="nav-item ">
            <a href="{{route('admin.aduan')}}" class="nav-link {{ url('/admin/aduan') == request()->url() ? 'active' : '' }}">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>Pengaduan Masyarakat</p>
            </a>
          </li>
          @endif
          
          <?php
          $menu = MenuUser::where('group_id',$group_id)->where('menu','Modul Users')->get();
          ?>
          @if ($menu->COUNT() <> 0)
          <li class="nav-item ">
            <a href="{{route('admin.user')}}" class="nav-link {{ url('/admin/user') == request()->url() ? 'active' : '' }}">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>Modul Users</p>
            </a>
          </li>
          @endif
          
         

          <li class="nav-item">
            <a href="{{ route('logout') }}" class="nav-link" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
              <i class="nav-icon fas fa-power-off"></i>
              <p>Logout</p>
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>